export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};


export const CartActionTypes = {
  FETCH_CART: "FETCH_CART",
  ADD_CART: "ADD_CART",
  REMOVE_PRODUCT_CART: "REMOVE_PRODUCT_CART",
};